### ISSUE TITLE
Create index on dropped table throws error

### ISSUE THREAD

**Issue by jrlegrand** [coderxio/sagerx#314]
# Problem Statement
Get error when running rxnorm_historical DAG when (I think) the rxnorm_historical table doesn't currently exist and the DAG is being run for the first time(?).  See error message below.

`psycopg2.errors.UndefinedTable: relation "***_lake.rxnorm_historical" does not exist`

`[SQL: CREATE INDEX IF NOT EXISTS idx_rxnorm_historical_ndc_end_date ON sagerx_lake.rxnorm_historical (ndc, end_date)]`

# Criteria for Success
Indexes should be created successfully for tables that are being created by a DAG for the very first time, and also tables that have been created previously.

# Additional Information

See `load_df_to_pg` function in https://github.com/coderxio/sagerx/blob/main/airflow/dags/sagerx.py

![image](https://github.com/user-attachments/assets/ba0b729e-76fc-4688-9ecf-9072030caf40)

Error log:

```
[2024-07-24, 06:28:51 UTC] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-24, 06:28:51 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "***_lake.rxnorm_historical" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rxnorm_historical/dag_tasks.py", line 50, in extract_ndc
    load_df_to_pg(pd.concat(dfs),"sagerx_lake","rxnorm_historical","replace",index=False, create_index=True, index_columns=['ndc','end_date'])
  File "/opt/airflow/dags/sagerx.py", line 170, in load_df_to_pg
    engine.execute(f'CREATE INDEX IF NOT EXISTS idx_{table_name}_{"_".join(index_columns)} ON {schema_name}.{table_name} ({columns_str})')
  File "<string>", line 2, in execute
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 468, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3257, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    future=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1676, in _exec_driver_sql
    distilled_parameters,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "***_lake.rxnorm_historical" does not exist

[SQL: CREATE INDEX IF NOT EXISTS idx_rxnorm_historical_ndc_end_date ON sagerx_lake.rxnorm_historical (ndc, end_date)]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-07-24, 06:28:51 UTC] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=rxnorm_historical, task_id=extract_ndc, execution_date=20240724T015753, start_date=20240724T052229, end_date=20240724T062851
[2024-07-24, 06:28:51 UTC] {standard_task_runner.py:105} ERROR - Failed to execute job 81 for task extract_ndc ((psycopg2.errors.UndefinedTable) relation "***_lake.rxnorm_historical" does not exist

[SQL: CREATE INDEX IF NOT EXISTS idx_rxnorm_historical_ndc_end_date ON sagerx_lake.rxnorm_historical (ndc, end_date)]
(Background on this error at: https://sqlalche.me/e/14/f405); 595050)
[2024-07-24, 06:28:52 UTC] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-24, 06:28:52 UTC] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by jrlegrand** [comment]
Currently only affects rxnorm_historical DAG
