### ISSUE TITLE
Make rate limiting work with RxClass

### ISSUE THREAD

**Issue by jrlegrand** [coderxio/sagerx#331]
# Problem Statement
See related branch jrlegrand/rxclass-rework.

RxClass API has a rate limit of 20 calls / second.

There's about 123,246 API calls.

`[2024-11-22, 01:14:28 CST] {logging_mixin.py:137} INFO - URL List created of length: 123246
`

I'm no mathematician, but 20 calls / second x 60 seconds / minute = 1200 calls / minute. 123,246 / 1200 calls / minute = 103 minutes or exactly 1 hour and 43 minutes.

When I run my branch locally, it runs for 1 hour and 43 minutes and errors out with the error below.

```
[2024-11-22, 02:58:01 CST] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rxclass/dag_tasks.py", line 41, in extract_rxclass
    rxclasses = response['rxclassDrugInfoList']['rxclassDrugInfo']
KeyError: 'rxclassDrugInfoList'
```

As I'm writing this, I think the issue is more about what happens after the API calls have completed - seeing as the time it ran is appropriate based on my #math above and the error seems to be about a KeyError.

Either way, this is not working - maybe the problem isn't with my rate limiting code, but either way it would be great to have other eyes on this.

# Criteria for Success
RxClass DAG runs in about 1 hour 45 minutes and does not error out.

# Additional Information
https://lhncbc.nlm.nih.gov/RxNav/TermsofService.html

**Comment by saywurdson** [comment]
@jrlegrand it looks like the reason why the code is failing is because it does not handle cases where the API response lacks the 'rxclassDrugInfoList' key, (meaning there is no class data associated with the concept) leading to a KeyError. The problem is happening in the `process_concept` function. We just need to figure out how to handle this situation more elegantly.

Potential solutions off the top of my head:
1. We can add some kind of logging to identify the concepts that don't have class data in the terminal
2. We can just skip these concepts
3. We can add them to the final table but all the className and other class info will be blank. 

Let me know what you think would be the best solution moving forward and I'll see how I can fix the code so that it works

**Comment by jrlegrand** [comment]
I pushed up some code to the branch.  It works - see my most recent commit message. It runs in 2.5 hours which could be optimized I'm sure.  I noticed when the key doesn't exist, it returns an empty object {}. Also I spot checked against RxClass for may_treat "Multiple Myeloma" and SageRx had 3 fewer IN drugs than the RxClass UI online.  These ones were missing in SageRx.
IN	3639	doxorubicin
IN	612937	interferon alfa-n3
IN	72257	interferon beta-1b
https://mor.nlm.nih.gov/RxClass/search?query=Multiple%20Myeloma%7CDISEASE&searchBy=class&sourceIds=&drugSources=atc1-4%7Catcprod%2Cepc%7Cdailymed%2Cdisease%7Cmedrt%2Cchem%7Cdailymed%2Cmoa%7Cdailymed%2Cpe%7Cdailymed%2Cpk%7Cmedrt%2Ctc%7Cfmtsme%2Cva%7Cva%2Cdispos%7Csnomedct%2Cstruct%7Csnomedct%2Ctherap%7Csnomedct%2Cschedule%7Crxnorm

**Comment by jrlegrand** [comment]
Hmm... I don't see an IN listed for the may_treat Multiple Myeloma relationship in the API (I'm only seeing the PIN) so maybe it's not an issue with our code. Maybe it's some weird thing with RxClass UI?

API https://rxnav.nlm.nih.gov/REST/rxclass/class/byRxcui.json?rxcui=612937

NOTE: the only may-treat relation is a PIN with RXCUI 72258.

I suspect what the RxClass UI is doing is mapping PIN to IN if an IN doesn't already exist in the list. In other words, I see a lot of PINs that kind of have "sister" INs... except for these 3. They only show up as PINs. But you can map from PIN to IN to get the IN if that's preferred.

RxClass https://mor.nlm.nih.gov/RxClass/search?query=elotuzumab&searchBy=drug&sourceIds=&drugSources=atc1-4%7Catcprod%2Cepc%7Cdailymed%2Cdisease%7Cmedrt%2Cchem%7Cdailymed%2Cmoa%7Cdailymed%2Cpe%7Cdailymed%2Cpk%7Cmedrt%2Ctc%7Cfmtsme%2Cva%7Cva%2Cdispos%7Csnomedct%2Cstruct%7Csnomedct%2Ctherap%7Csnomedct%2Cschedule%7Crxnorm

RxNav https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=72258

**Comment by jrlegrand** [comment]
Number of rows by rela_source
![image](https://github.com/user-attachments/assets/27242d4b-b63f-4fe0-9e85-254834a20d38)

**Comment by saywurdson** [comment]
https://github.com/coderxio/sagerx/pull/333

**Comment by jrlegrand** [comment]
@coussens - I did consider that for a moment. It seemed pretty resource intensive (below). It might be a good way to get RxClass data and RxNorm Historical NDC data though - those are the most intensive API calls I have to make.

SYSTEM REQUIREMENTS
-------------------

 - 12 gigabytes of memory to devote to a container platform (e.g., Docker)

 - 100 gigabytes of disk space

 - Docker Desktop,
   or another OCI-compatible platform (in which case you
   may take the included docker-compose.yml file as an example).

**Comment by coussens** [comment]
@jrlegrand I think those system requirements are far higher than the required resources, especially since anyone running SageRx already has Docker installed. On my Mac, the images and volumes for the RxNorm container I have running on my Mac looks like they only take up about ~7GB of disk space combined. Also, the zipped docker container that's hosted on the NLM website is only about ~700MB, so it doesn't take all that long to download.

**Comment by jrlegrand** [comment]
Good points. I think it comes down to balancing speed with complexity. Given that it doesn't really matter if it takes 2 hours to run if I can schedule it to run automatically overnight once per week, it's hard to take a different approach to getting data just for RxClass.

**Comment by coussens** [comment]
Yeah, you're right -- it is quite a bit more of a lift just for RxClass. Too bad they don't include the ATCPROD/RxClass mapping in the RxNorm files! It's unclear to me why they don't -- do you have any insight into why this might be?

**Comment by yevgenybulochnik** [comment]
Food for thought, the rxnav in a box zip file has a mariadb container and consumes a file called 02_data.sql. Might be able to back into the rxclass dataset by parsing this sql file. On another note it may be worth exploring the mariadb data to see if it could be mined for anything else. Parsing the sql file file might not be easy its a 3gb file, but might be worth it.

**Comment by jrlegrand** [comment]
@yevgenybulochnik - very interesting idea...

So that file (`02_data.sql`) looks like it basically loads up tables that might be the same tables that RxNorm's (and RxClalss's???) APIs use - particularly interesting to me are all the tables about historical NDCs and RXCUIs as well as all the RxClass-related tables. There's also a table that appears to be NLM's version of making it easier to go from one TTY RXCUI to another TTY RXCUI like rxnrela but easier b/c it pulls in the RXCUIs.

This is worth exploring maybe as a separate issue.  I'll prob end up copying this stuff into a separate issue eventually.

I went through the SQL file and tried to find all the table names that get generated.  See below for table names and random notes.

Tables:

- ALLNDC_HISTORY
- ALLRXCUI_HISTORY2
- BOSS_HISTORY2
- CLASS_DRUGSNG
- CLASS_HDR_CONCEPTID
- CLASS_MEMBER_COUNTSNG
- CLASS_NODESNG
- CLASS_SRC_NAMENG
- CLASS_SYNSNG
- DFG_HISTORY2
- DataInfo - apparently only stores the release date for RxTerms (i.e. RxTerms202501)
- INGRED_HISTORY2
- MERGE_HISTORY2
- NDCHistory
- NDCProperties - looks like a messier version of FDA NDC Directory? - many rows
- OTHER_NDC_LABELS
- PACK_HISTORY2 - looks like just a few rows?
- RXCLASS_META - metadata about what's in RxClass?
- RXCONCEPTINFO2
- RXNATOMARCHIVE2
- RXNCONSO
- RXNORM_HISTORY2
- RXNREL_RXNORM
- RXNSAB
- RXNSAT - lots of rows
- RxTerms
- build_number
- drug_class_linksNG
- finddrugs - no rows in here?
- ndc_history_stages
- ndc_source_map
- ndc_sources
- ndc_status
- ndc_status_priority
- rxclass_sources
- rxclass_typesNG
- rxcui_mappings_1
- rxcui_mappings_2
- rxnav_tables_version
- rxnorm_display_terms
- rxnorm_display_terms
- rxnorm_drug_tty
- rxnorm_normstr
- rxnorm_propcat
- rxnorm_procatlink
- rxnorm_proppres
- rxnorm_props
- rxnorm_rela
- rxnorm_relations - holy shit - i think this is how they easily generate the From->To relationship tables
- rxnorm_sab_source
- rxnorm_sts_labels
- rxnorm_version
- rxterms_version
- ttys

Notes:
Not sure if ALLNDC_HISTORY or NDCHistory are the better tables for RxNorm Historical for Historical NDCs.
